name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build:dev
        env:
          GATSBY_SITE_NAME: ${{ secrets.SITE_NAME }}
          GATSBY_BASE_URL: ${{ secrets.BASE_URL }}

      - name: Test app
        run: yarn test
