name: Build and Deploy to Netlify

on:
  push:
    branches:
      - develop
    paths:
      - "src/**"
      - "gatsby-*.js"
      - ".env.development"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Build site
        env:
          GATSBY_SITE_NAME: Sulhan Jauhary
          GATSBY_BASE_URL: https://ngeblog-yukz.netlify.app
        run: |
          yarn install --production
          yarn build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public -p
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
