name: Netlify Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          version: 12.x

      - name: Build site
        run: |
          yarn install --production
          yarn build

      - name: Deploy to netlify
        uses: nwtgck/actions-netlify@v1.1.11
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
        with:
          publish-dir: "./public"
          production-branch: develop
          deploy-message: "${{ github.event.head_commit.message }}"
