name: Build and Deploy to Netlify

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Build site
        run: |
          yarn install --production
          yarn build

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public -p
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_APP_ID }}
